import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import { config } from "@fortawesome/free-solid-svg-icons"
// import "@fortawesome/fontawesome-svg-core/styles.css"
// config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Ticket App",
  description: "Generated by Archil Milorava",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
        <NavBar />
        <div className="flex-grow overflow-y-auto bg-page text-default-text">
        {children}
        </div>
        </div>
        </body>
    </html>
  );
}
